name: flutter_sendbird
description: A new flutter plugin project.
version: 0.0.1
author:
homepage: https://github.com/sensestar/flutter_sendbird
repository: https://github.com/sensestar/flutter_sendbird

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^0.8.3
  json_annotation: ^3.0.1
  http: ^0.12.0+4 
  intl: ^0.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.10.1

flutter:

  plugin:
    platforms:
      android:
        package: com.sstar.flutter_sendbird
        pluginClass: FlutterSendbirdPlugin
      ios:
        pluginClass: FlutterSendbirdPlugin

  